# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Ghidra dark theme

env:
  GHIDRA_VERSION: 9.2.3
  GHIDRA_DATE: 20210325

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Set up Ghidra
        run: |
          current_dir=$PWD
          cd ..
          curl -O "https://ghidra-sre.org/ghidra_${GHIDRA_VERSION}_PUBLIC_${GHIDRA_DATE}.zip"
          unzip -q "ghidra_${GHIDRA_VERSION}_PUBLIC_${GHIDRA_DATE}.zip"
          echo "GHIDRA_INSTALL_DIR=$PWD/ghidra_${GHIDRA_VERSION}_PUBLIC" >> $GITHUB_ENV
          rm "ghidra_${GHIDRA_VERSION}_PUBLIC_${GHIDRA_DATE}.zip"
          cd $current_dir
        working-directory: ${{ env.TMPDIR }}
      - name: Build plugin with Gradle
        run: |
          ./gradlew
          plugin_date=$(find dist -name '*.zip' | awk -F '_' '{print $4}')
          echo "ASSET_PATH=$(find dist -name '*.zip')" >> $GITHUB_ENV
          echo "ASSET_NAME=$(find dist -name '*.zip' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
          last_tag=$(git tag -l "$plugin_date.*" | tail -n 1)
          if [ ! -z "$last_tag" ]; then
              echo "$last_tag" | awk -F '.' '{print "PLUGIN_TAG=" $1 "." $2+1}' >> $GITHUB_ENV
          else
              echo "PLUGIN_TAG=$plugin_date.0" >> $GITHUB_ENV
          fi
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ env.PLUGIN_TAG }}
          tag_name: ${{ env.PLUGIN_TAG }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload to Releases
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.ASSET_PATH }}
          asset_name: ${{ env.ASSET_NAME }}
          asset_content_type: application/zip
